name: luna-tv-night

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: luna-tv-night
          path: build/app/outputs/flutter-apk/app-release.apk
